# Generated by Django 3.2.5 on 2021-07-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='EntryModel',
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='TopicModel',
        ),
    ]
