# Generated by Django 3.2.5 on 2021-07-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_topicmodel_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicmodel',
            options={'verbose_name_plural': 'Topics'},
        ),
    ]
